---
- name: Update package cache
  ansible.builtin.package:
    update_cache: true
- name: Install nftables pkg
  ansible.builtin.package:
    name: "{{ nftables_pkg }}"
    state: present
- name: Deploy nftables unit
  ansible.builtin.template:
    src: nftables.service.j2
    dest: "{{ nftables_systemd_unit_location }}/nftables.service"
    owner: root
    group: root
    mode: '0755'
- name: Copy test nftables config file
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf.new
    owner: root
    group: root
    mode: '0755'
- name: Test newly created config file
  ansible.builtin.command: "nft --check --file /etc/nftables.conf.new"
- name: Deploy rules config file
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0755'
- name: Copy nftable-service bin
  copy:
    src: nftables-service
    dest: /usr/local/sbin/nftables-service
    owner: root
    group: root
    mode: '0755'
- name: Enable nftables on boot
  ansible.builtin.systemd_service:
    name: "nftables"
    enabled: true
    daemon_reload: true
