---
iperf3_server_pkg:
  - iperf3
iperf3_server_pkg_state: "present"

iperf3_server_options: "--server"

iperf3_server_systemd_enabled: true
iperf3_server_systemd_state: "started"
iperf3_server_systemd_unit_file_location: "/etc/systemd/system/iperf3-server.service"

iperf3_server_user: "iperf"
iperf3_server_group: "iperf"
