---
- name: Interfaces config
  hosts: iperf-computes
  become: yes
  roles:
    - networkd_systemd

- name: NFTables config
  # TODO change later to all
  hosts: iperf-computes
  become: yes
  roles:
    - nftables

- name: Limit gre bandwidth using tc
  hosts: iperf-computes
  become: yes
  roles:
    - traffic_control

- name: Launch iperf3-server on iperf-computes
  hosts: iperf-computes
  become: yes
  roles:
    - iperf3_server

- name: Install node_exporter on iperf-computes
  hosts: iperf-computes
  become: yes
  roles:
    - node_exporter

- name: Install docker on monitoring compute
  hosts: monitoring-computes
  become: yes
  roles:
    - docker

- name: Launch monitoring stack on monitoring-computes
  hosts: monitoring-computes
  become: yes
  vars:
    # From iperf-computes we extract the ansible_host ip address and then replacing the end of the string '$' with port ':9100' (node_exporter)
    _prometheus_scrape_targets: "{{ groups['iperf-computes'] | map('extract', hostvars, 'ansible_host') | map('regex_replace', '$', ':9100') | list }}"
  roles:
    - monitoring
